version: '3.9'

services:
    app:
        image: 6053537/portainer-ce
        networks:
            - dokploy-network
        ports:
            - 9000
            - 9443
        restart: always
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/docker/portainer:/data"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.docker.entrypoints=websecure"
            - "traefik.http.routers.docker.tls.certResolver=letsencrypt"
            - "traefik.http.routers.docker.rule=Host(`docker.828384.xyz`)"
            - "traefik.http.services.docker.loadbalancer.server.port=9000"

networks:
    dokploy-network:
        external: true